### ISSUE TITLE
Feature Request - 1

### ISSUE THREAD

**Issue by danihax** [mizarc/bell-claims#101]
First thing I would like to thank you guys for creating an item based land claim system, I was able to implement it in my NPC shops!
The plugin is working as intended. While it's still relatively new, I would like to add some suggestions.
      

- A config file that will allow the server owner to modify a default configuration for all claims that are created. I would like to have the claims to have Chest permissions turned on for all claims, while everything else is turned off. Essentially I would like to restrict players from protecting chests. I run a PvP server with raiding, so it will help to have this functionality.

    

- A jail feature for landowners: If a trespasser is caught attempting to steal or interfere with a landowner's property, and the landowner successfully kills them, the trespasser will be jailed in a designated area or partition within the owner's claim. Once inside the jail, the trespasser cannot interact with any surrounding blocks. The landowner can also set a custom jail sentence duration as they see fit.

     

- add on for DynMap - visually see the claims in a colored-transparent square with their name.

   

- Name of claim popping up in text chat or on screen.

(this was also posted on Gitlab)

**Comment by mizarc** [comment]
Hello and thanks for appreciating the work that's put into this! I'll take into account the feature set you've suggested and split them off into separate issue pages just for better tracking, but I'd like to do a bit of discussion here first.

> A config file that will allow the server owner to modify a default configuration for all claims that are created

This is definitely something that could be useful to have. I will likely implement a claim permission/flag blacklist in the config, maybe implement a server permission system to allow certain players to use certain claim permissions/flags.

> A jail feature for landowners

This seems a little out of scope for this plugin. The core focus behind Bell Claims is land claiming. If someone is able to interfere with a claim in a way that the owner does not want, that either means the claim permissions the owner has set are too permissive, or a bug has been discovered that needs to be patched.

I do understand that you want to use this plugin in a PvP raiding focused server where such functionality may be useful to have. This may be something that could be done in an addon, which will be possible to do once I've completed the external API hooks. If I have the time to do so, I could consider approaching it myself, but I have other priorities to address at the moment. Maybe share the plugin around to get some attention and someone may be interested in making such a thing.

> add on for DynMap

Already planned!

> Name of claim popping up in text chat or on screen.

This would be useful to have, I'll definitely try to implement this with varying options of text placement for server owners to decide on.

**Comment by danihax** [comment]
Awesome! I'll be posting any issues I encounter, hopefully nothing ground breaking. 

> I will likely implement a claim permission/flag blacklist in the config, maybe implement a server permission system to allow certain players to use certain claim permissions/flags.

Blacklist in the config should work! This can apply globally to all claims.
If going the "server permission system" route, maybe using a system like LuckPerms can help sort out permissions for admins and default players. 

> This may be something that could be done in an addon, which will be possible to do once I've completed the external API hooks. If I have the time to do so, I could consider approaching it myself, but I have other priorities to address at the moment. Maybe share the plugin around to get some attention and someone may be interested in making such a thing.

Got it! No biggie, I'll see what I can do on my end. You got a lot on your plate already, you've been great help already with this plugin release!

> I'll definitely try to implement this with varying options of text placement for server owners to decide on

sounds good!

**Comment by mizarc** [comment]
I've created separate issue pages for the changes I'm going to follow up with. See #106 #107 #109 to discuss changes if you'd like. Closing this issue page now.
