### ISSUE TITLE
Sand does not update in claims

### ISSUE THREAD

**Issue by lmichaelis** [mizarc/bell-claims#19]
**Observed behaviour:**

Sand and gravel don't fall in claims.

![2024-07-25_17 30 23](https://github.com/user-attachments/assets/48f02933-9bba-4a28-af44-252f47b1fa23)

**Expected behaviour:**

Sand and gravel observe gravity and fall to the ground when placed in the air.

**Steps to reproduce:**

Create a new claim, place sand or gravel in the air, observe it not falling.

**Comment by mizarc** [comment]
Looks like falling entities was caught as part of the mob griefing check. Should be an easy enough fix to exclude them.
