### ISSUE TITLE
Update needed to support 1.21.1

### ISSUE THREAD

**Issue by marghost** [mizarc/bell-claims#33]
Issue : When clicking on a new bell to setup a claim, it doesn't work.

Server : purpurmc lastest (purpur-1.21.1-2297.jar)

Error output in console:
`22.08 15:32:35 [Server] ERROR [BellClaims] Exception while handling click event in inventory 'Claim Creation', slot=4, item=BELL
22.08 15:32:35 [Server] INFO com.github.stefvanschie.inventoryframework.exception.UnsupportedVersionException: The server version provided is not supported
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.util.version.Version.getVersion(Version.java:282) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.gui.type.AnvilGui.<init>(AnvilGui.java:81) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimNamingMenu(ClaimManagementMenu.kt:86) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimNamingMenu$default(ClaimManagementMenu.kt:84) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/dev.mizarc.bellclaims.interaction.menus.ClaimManagementMenu.openClaimCreationMenu$lambda$4(ClaimManagementMenu.kt:79) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.gui.GuiItem.callAction(GuiItem.java:179) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.pane.StaticPane.click(StaticPane.java:238) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:205) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.gui.type.ChestGui.click(ChestGui.java:161) ~[BellClaims-0.2.2.jar:?]
22.08 15:32:35 [Server] INFO at BellClaims-0.2.2.jar/com.github.stefvanschie.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:82) ~[BellClaims-0.2.2.jar:?]`

Thanks for your time.

**Comment by mizarc** [comment]
Thanks for letting me know about this incompatibility with the latest MC version. Issue has been fixed as of pull request #34 and a patch version will be released very shortly.
