### ISSUE TITLE
Add initial claim size config option

### ISSUE THREAD

**Issue by RodargDev** [mizarc/bell-claims#36]
I want the initial claim size to be smaller instead of the 5x5. i thought the minimum claim size would also help here but it does not, it only allows me to make the claimed land smaller

**Comment by RodargDev** [comment]
This is also the case for extensions, could you maybe make it possible for an amdin to also extend other people claims? Any idea how much time this will cost ya im currently using it on an SMP with avg 30/40 players so if you have the time please add it quick (ip: boffy.online)

**Comment by mizarc** [comment]
Definitely no ETA I can give right now until I figure out what would be required to implement such a feature. It would have to handle the fetching of a different player's metadata and make use of their limits on their behalf, which could take a bit of work. There's also a good number of other pending features that will go into the next feature version, but I'll let you know if I can make an experimental build of this at the earliest possible time.

**Comment by RodargDev** [comment]
Aaah alright well yeah the admin extending other peoples claims isnt that necessary but having it not require 5x5 with claims would be nice. Ill be waiting for updates :)

**Comment by RodargDev** [comment]
@mizarc any chance i can add you on something like discord? found another bug and rather not place it in the issues here
