### ISSUE TITLE
WorldGuard plugin breaks claiming land

### ISSUE THREAD

**Issue by RodargDev** [mizarc/bell-claims#37]
When i add the worldguard plugin to my server i cannot claim land. I can enter the bell menu for claiming but i cannot confirm it. is this expected behavior or an actual bug?

**Comment by mizarc** [comment]
Never tested with WorldGuard, so I'll have to see what kind of conflicts are happening here.

**Comment by mizarc** [comment]
I am not experiencing any WorldGuard conflicts. Can you show me any errors in the console so I can see what's going on? Make sure you're running the latest release version too.

**Comment by RodargDev** [comment]
Ill try this in a bit, might have been an version issue indeed. Ill get back to you when ive tried
