### ISSUE TITLE
Bell Duplication using move claim

### ISSUE THREAD

**Issue by Dyljyn** [mizarc/bell-claims#81]
_One of my players found the following bug._

https://github.com/user-attachments/assets/92559a33-62ed-4b3d-93db-d1d3726be360

## Current Behavior

Upon choosing to "Move Claim", a bell is received in their inventory. When the player breaks the bell of their claim, they are also given the broken bell back. They now have duplicated a bell.

## Expected Behavior

The "Move Claim" bell is removed from the inventory after the claim is broken

**Comment by mizarc** [comment]
Oh good catch! Should be an easy enough fix to detect the move bell item based on its metadata.
